version: "3.9"
services:
  wallet:
    image: quay.io/tarilabs/tari_console_wallet
    build:
      context: ./..
      dockerfile: buildtools/console_wallet.Dockerfile
      args:
        ARG WALLET_ARCH: x86-64
    environment:
      TARI_LOG_CONFIGURATION: "/var/tari/config/log4rs.yml"
      WAIT_FOR_TOR: 0
    command: ["start_wallet.sh", "-c", "/var/tari/config/config.toml", "-b", "/var/tari"]
    depends_on:
      - tor
    volumes:
      - $HOME/.tari/config:/var/tari/config
      - $HOME/.tari/data:/var/tari/wallet
  tor:
    image: quay.io/tarilabs/tor:latest
    ports:
      - 9050:9050
      - 9051:9051
  base_node:
    image: quay.io/tarilabs/tari_base_node
    build:
      context: ./..
      dockerfile: buildtools/base_noded.Dockerfile
      args:
        ARG WALLET_ARCH: x86-64
    environment:
      TARI_LOG_CONFIGURATION: "/var/tari/config/log4rs.yml"
      WAIT_FOR_TOR: 0
      TARI_NETWORK: weatherwax
    command: [ "start_base_node.sh", "-c", "/var/tari/config/config.toml", "-b", "/var/tari/base_node", "-d" ]
    depends_on:
      - tor
    volumes:
      - $HOME/.tari/config:/var/tari/config
      - $HOME/.tari/base_node:/var/tari/base_node
      - $HOME/.tari/log:/var/tari/log
#  xmrig:
#  sha3-miner:
#  pool-worker:
#  pool-operator:

#volumes:
#  config:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: $HOME/.tari/config
#  data:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: $HOME/.tari/data